spring:
  application:
    name: docwf-workflow-backend

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

logging:
  level:
    com.docwf: INFO
    org.hibernate.SQL: INFO
    org.quartz: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Custom properties
app:
  workflow:
    trigger-interval: 15 # minutes
    file:
      upload-dir: ./uploads
      max-size: 10MB
  security:
    jwt:
      secret: ${JWT_SECRET:your-secret-key-here}
      expiration: 86400000 # 24 hours

# OpenAPI Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
  packages-to-scan: com.docwf.controller
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
