spring:
  datasource:
    url: jdbc:oracle:thin:@${DB_HOST:localhost}:${DB_PORT:1521}:${DB_SID:XE}
    username: ${DB_USERNAME:workflow_user}
    password: ${DB_PASSWORD:workflow_pass}
    driver-class-name: oracle.jdbc.OracleDriver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: false
        envers:
          audit_table_suffix: _AUD
          revision_field_name: REV
          revision_type_field_name: REVTYPE
          store_data_at_delete: true
          default_schema: ${DB_SCHEMA:WORKFLOW_USER}
    
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org.quartz.scheduler.instanceName: WorkflowScheduler
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.oracle.OracleDelegate
      org.quartz.jobStore.tablePrefix: QRTZ_
      org.quartz.jobStore.isClustered: true
      org.quartz.jobStore.clusterCheckinInterval: 20000
      org.quartz.jobStore.misfireThreshold: 60000
      org.quartz.jobStore.txIsolationLevelSerializable: true
      org.quartz.jobStore.selectWithLockSQL: SELECT * FROM {0}LOCKS WHERE LOCK_NAME = ? FOR UPDATE
      org.quartz.jobStore.txIsolationLevelReadCommitted: false
      org.quartz.jobStore.acquireTriggersWithinLock: true
      org.quartz.jobStore.dataSource: quartzDataSource
      org.quartz.dataSource.quartzDataSource.driver: oracle.jdbc.OracleDriver
      org.quartz.dataSource.quartzDataSource.URL: ${spring.datasource.url}
      org.quartz.dataSource.quartzDataSource.user: ${spring.datasource.username}
      org.quartz.dataSource.quartzDataSource.password: ${spring.datasource.password}
      org.quartz.dataSource.quartzDataSource.maxConnections: 5
      org.quartz.threadPool.class: org.quartz.simpl.SimpleThreadPool
      org.quartz.threadPool.threadCount: 10
      org.quartz.threadPool.threadPriority: 5
      org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread: true

logging:
  level:
    com.docwf: INFO
    org.hibernate.SQL: WARN
    org.quartz: INFO
